### ISSUE TITLE
Terminal-plus is broken

### ISSUE THREAD

**Issue by laughedelic** [inkytonik/atom-sbt#12]
Terminal-plus package seems to be kind of abandoned. Since Atom 1.7 there are a lot of reports that it doesn't work. What do you think about switching to a more maintained fork?

https://github.com/jeremyramin/terminal-plus/issues/223

**Comment by inkytonik** [comment]
Thanks, yes that is probably a good idea. I will try to take a look at it soon.

**Comment by inkytonik** [comment]
Sorry for not getting around to this sooner. Can I ask you to try 1743f9ca258414616e120165d89b9a616bd8b62e? As far as I can see that version is working fine in Atom 1.8.0-beta4 so I'm hopeful that it will work for you too. If it looks ok, I will publish the next version soon with these changes.

**Comment by inkytonik** [comment]
I tested this change with 1.7.4 and 1.8.0-beta4 and it appears to work. The change is in version 0.8.0 so closing for now. Please reopen if there is still a problem.
