### ISSUE TITLE
How do I get linter errors to be inline

### ISSUE THREAD

**Issue by i-am-the-slime** [inkytonik/atom-sbt#15]
This is possibly a dumb question but I would really like to see all errors under the line they belong to and not at the bottom of the file. Is this possible? If so, how?

**Comment by inkytonik** [comment]
The sbt package just uses the Atom linter package, so you should be able to configure what you want using that package. E.g., "Show Inline Error Tooltips". Is that what you mean?

**Comment by inkytonik** [comment]
Closing for now since it doesn't seem to be a problem. Please reopen if I'm missing something.
