### ISSUE TITLE
Uncaught TypeError: this.registerIndie is not a function

### ISSUE THREAD

**Issue by tpolecat** [inkytonik/atom-sbt#19]
[Enter steps to reproduce:]

1. press option+cmd+O

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package 0.10.0

### Stack Trace

Uncaught TypeError: this.registerIndie is not a function

```
At /Users/rnorris/.atom/packages/sbt/lib/sbt.coffee:139

TypeError: this.registerIndie is not a function
    at Object.getOrMakeCurrentProject (/packages/sbt/lib/sbt.coffee:139:19)
    at /packages/sbt/lib/sbt.coffee:76:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:56.1.0 settings-view:open (atom-pane.pane.active)
     -2:44.2.0 core:confirm (input.hidden-input)
     -1:12.2.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -1:08.8.0 sbt:toggle-panel (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
activate-power-mode 1.1.0 
autocomplete-ctags 0.4.1 
browser-plus 0.0.76 
copy-as-rtf 0.9.3 
hyperclick 0.0.37 
intentions 1.1.2 
language-fortran 2.0.15 
language-scala 1.1.8 
linter 1.11.16 
platformio-ide-terminal 2.5.0 
sbt 0.10.0 
select-rectangle 1.0.2 
```

**Comment by inkytonik** [comment]
This looks to be an incompatibility with the linter package. The sbt package now uses Linter V2 but you have V1. When installing the sbt package from scratch it should install the required packages, so I'm not sure why that didn't happen for you. Did you install in the regular way?

**Comment by tpolecat** [comment]
Hm I updated Linter which then asked me to updated some other things, and I ended up at #18

**Comment by tpolecat** [comment]
Oh, also I installed using the UI inside Atom. I don't know if this is the "regular" way or not. I sure hope so.

Anyway, closing this.

**Comment by inkytonik** [comment]
Hmm, as far as I am aware installing from inside Atom should've caused it to install Linter V2 since that's what the sbt package requires. But to be honest I'm not sure how things are supposed to work if some packages require V1 and others V2.
