### ISSUE TITLE
Replace errors from previous run only when the new run is finished

### ISSUE THREAD

**Issue by i-am-the-slime** [inkytonik/atom-sbt#21]
Very nice plugin!

Right now I find myself fixing errors that the compiler issues and then hitting save to see if I did it right.
Because scala compiles so horribly slowly, I would like to take a look at the other errors that are issued in the meantime.
However after hitting save, the errors immediately disappear and only reappear once compile is done.
Can I do anything about this?

**Comment by i-am-the-slime** [comment]
So it seems like this plugin is clearing the messages too quickly (https://github.com/steelbrain/linter/issues/1457#issuecomment-299929802)

**Comment by inkytonik** [comment]
Yep, I think you are right. I will try to address this in the next version (should be soonish).

**Comment by inkytonik** [comment]
I've made this change in 3f753e967ef4fdf64c69d734ae087cf32d39c64b which is part of 0.11.0. Please let me know how it goes for you here.

**Comment by inkytonik** [comment]
Oh and thanks for the positive feedback!
