### ISSUE TITLE
Linter errors not cleared in some cases.

### ISSUE THREAD

**Issue by tpolecat** [inkytonik/atom-sbt#22]
Kind of a dumb question. How do I make linter errors go away after I have fixed the code and it compiles clean? I kind of expected them to go away automatically.

**Comment by inkytonik** [comment]
They are supposed to go away automatically and they do in my setup :-) Do you have a project where they always stick around that I could try?

**Comment by tpolecat** [comment]
Yep, [here](https://github.com/tpolecat/test) is what I think is a minimal reproduction. It's quite crazy.

Load up that project, then `~compile`. Delete the `j` in `object` and save, then undo and save again. The linter panel will not be cleared, or at least it isn't on my setup.

This seems to be an interaction of two things:
- It must be a fast compile where sbt only says `[success] ...` without any `[info] Compiling ...` message.
- If only happens when using [Coursier](https://github.com/coursier/coursier) for dependency management. (!)

If you comment out Coursier in `plugins.sbt` and reload you will find that everything works.

I have absolutely no idea. I apologize for discovering this. This is the kind of thing that makes me want to quit programming and open a bait shop.

**Comment by inkytonik** [comment]
Thanks :-). That's very useful (and weird). I'll take a look as soon as I can.

**Comment by inkytonik** [comment]
It seems that the Coursier plugin causes some of the sbt messages to change a bit. In this case it seems that an extra escape sequence causes the sbt package's matching to not spot the final success message (and hence not update the linter messages).

I've got no idea why that message changes in this situation. I'm not sure I want to know :-)

Anyway, I've released 0.12.0 that relaxes the matching a bit and seems to cope with this situation as well as retaining matching when Coursier is not used. Can you try it out and let me know how it goes?

**Comment by tpolecat** [comment]
Hey it works! Thanks!

**Comment by inkytonik** [comment]
Excellent! Thanks again for the report.
