### ISSUE TITLE
sbt 1.0?

### ISSUE THREAD

**Issue by tpolecat** [inkytonik/atom-sbt#23]
It looks like atom-sbt can't quite grok sbt 1.0 output. It understands when commands are running (the pulsing yellow ball that turns green works) but it doesn't seem to see compilation errors.

**Comment by inkytonik** [comment]
Yep, I'm seeing this too. Will take a look soon.

**Comment by inkytonik** [comment]
It seems that sbt 1.x includes a column number in error/warning messages and these were causing the matching to fail. I've just pushed 0.13.0 which ignores them. For me it seems to work for sbt 1.x and sbt 0.13. Please let me know how it goes for you.

**Comment by tpolecat** [comment]
Will do, thanks!

**Comment by tpolecat** [comment]
Finally was able to update to sbt 1.0.3 and your 0.13 plugin seems to work perfectly. Thank you!

**Comment by inkytonik** [comment]
Excellent! Thanks for getting back to me.
