### ISSUE TITLE
Turn off auto-toggle

### ISSUE THREAD

**Issue by laughedelic** [inkytonik/atom-sbt#9]
Could you add a setting to turn off auto-toggle when a command is invoked? I'd like to run compile command and just get the linter errors list updated, without seeing the sbt output every time.

**Comment by inkytonik** [comment]
Thanks for the suggestion. I have added this capability and it will be in 0.7.0 which I expect to publish over the weekend.

**Comment by laughedelic** [comment]
Great! Thanks
